ALTER TYPE review_reason ADD VALUE IF NOT EXISTS 'payer_rejected';
ALTER TABLE batches ADD COLUMN IF NOT EXISTS manual_resolved INT NOT NULL DEFAULT 0;
ALTER TABLE batches ADD COLUMN IF NOT EXISTS label TEXT NOT NULL DEFAULT '';
ALTER TABLE batches ADD COLUMN IF NOT EXISTS kind TEXT NOT NULL DEFAULT 'batch'; -- batch | csv | synthetic
ALTER TABLE payers ADD COLUMN IF NOT EXISTS service_type_code TEXT NOT NULL DEFAULT '35';
ALTER TABLE payers ADD COLUMN IF NOT EXISTS plan_type TEXT NOT NULL DEFAULT 'PPO';
ALTER TABLE jobs DROP COLUMN IF EXISTS river_job_id;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS error_code TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS error_message TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS started_at TIMESTAMPTZ;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS resolved_at TIMESTAMPTZ;
CREATE INDEX IF NOT EXISTS idx_jobs_created_at ON jobs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_jobs_patient_id ON jobs(patient_id);
