// Package pdfreport renders patient records and practice reports as downloadable
// PDFs. No visual polish beyond what's needed to be legible and printable —
// this is a records export, not a design piece.
package pdfreport

import (
	"fmt"
	"io"
	"time"

	"github.com/go-pdf/fpdf"

	"coveragecheck/internal/db"
)

const (
	brandR, brandG, brandB = 14, 122, 95 // Verafy green
	textR, textG, textB    = 31, 41, 55
	mutedR, mutedG, mutedB = 107, 114, 128
)

func newDoc(title string) *fpdf.Fpdf {
	f := fpdf.New("P", "mm", "A4", "")
	f.SetTitle(title, true)
	f.SetMargins(15, 15, 15)
	f.AddPage()
	f.SetAutoPageBreak(false, 0)
	f.SetTextColor(textR, textG, textB)
	return f
}

func header(f *fpdf.Fpdf, title, subtitle string) {
	f.SetFillColor(brandR, brandG, brandB)
	f.Rect(0, 0, 210, 22, "F")
	f.SetTextColor(255, 255, 255)
	f.SetFont("Helvetica", "B", 16)
	f.SetXY(15, 6)
	f.CellFormat(180, 8, "Verafy", "", 1, "L", false, 0, "")
	f.SetFont("Helvetica", "", 9)
	f.SetX(15)
	f.CellFormat(180, 5, "Dental Insurance Verification", "", 1, "L", false, 0, "")
	f.SetTextColor(textR, textG, textB)
	f.SetY(28)
	f.SetFont("Helvetica", "B", 14)
	f.CellFormat(180, 8, title, "", 1, "L", false, 0, "")
	if subtitle != "" {
		f.SetFont("Helvetica", "", 10)
		f.SetTextColor(mutedR, mutedG, mutedB)
		f.CellFormat(180, 6, subtitle, "", 1, "L", false, 0, "")
		f.SetTextColor(textR, textG, textB)
	}
	f.Ln(3)
	f.SetDrawColor(220, 220, 220)
	f.Line(15, f.GetY(), 195, f.GetY())
	f.Ln(6)
}

func sectionTitle(f *fpdf.Fpdf, s string) {
	f.SetFont("Helvetica", "B", 11)
	f.SetTextColor(brandR, brandG, brandB)
	f.CellFormat(180, 7, s, "", 1, "L", false, 0, "")
	f.SetTextColor(textR, textG, textB)
	f.Ln(1)
}

func kv(f *fpdf.Fpdf, label, value string) {
	f.SetFont("Helvetica", "B", 9)
	f.SetTextColor(mutedR, mutedG, mutedB)
	f.CellFormat(45, 6, label, "", 0, "L", false, 0, "")
	f.SetFont("Helvetica", "", 9)
	f.SetTextColor(textR, textG, textB)
	f.CellFormat(0, 6, value, "", 1, "L", false, 0, "")
}

func footer(f *fpdf.Fpdf) {
	f.SetY(-15)
	f.SetFont("Helvetica", "I", 8)
	f.SetTextColor(mutedR, mutedG, mutedB)
	f.CellFormat(90, 6, "Generated by Verafy on "+time.Now().Format("Jan 2, 2006 3:04 PM"), "", 0, "L", false, 0, "")
	f.CellFormat(90, 6, "This is an internal record, not a bill.", "", 0, "R", false, 0, "")
}

func str(p *string) string {
	if p == nil || *p == "" {
		return "-"
	}
	return *p
}

// PatientPDF renders one patient's record: contact info, recent verification
// history, and (if present) their most recent coverage brief.
func PatientPDF(w io.Writer, p *db.Patient, jobs []db.Job) error {
	f := newDoc("Patient Record — " + p.Name)
	header(f, "Patient Record", p.Name)

	sectionTitle(f, "Patient Information")
	kv(f, "Full name", p.Name)
	kv(f, "Date of birth", p.DOB.Format("January 2, 2006"))
	kv(f, "Member ID", p.MemberID)
	kv(f, "Payer", fmt.Sprintf("%s (%s)", p.PayerName, p.StediPayerID))
	kv(f, "Email", str(p.Email))
	kv(f, "Phone", str(p.Phone))
	kv(f, "Last status", str(p.LastStatus))
	f.Ln(4)

	sectionTitle(f, fmt.Sprintf("Verification History (%d shown)", len(jobs)))
	if len(jobs) == 0 {
		f.SetFont("Helvetica", "I", 9)
		f.SetTextColor(mutedR, mutedG, mutedB)
		f.CellFormat(0, 6, "No verifications on record.", "", 1, "L", false, 0, "")
	} else {
		f.SetFont("Helvetica", "B", 8)
		f.SetFillColor(240, 240, 240)
		widths := []float64{32, 32, 45, 20, 51}
		heads := []string{"Date", "Status", "Payer", "Attempts", "Summary"}
		for i, h := range heads {
			f.CellFormat(widths[i], 6, h, "1", 0, "L", true, 0, "")
		}
		f.Ln(-1)
		f.SetFont("Helvetica", "", 8)
		for _, j := range jobs {
			summary := "—"
			if j.ErrorMessage != nil {
				summary = *j.ErrorMessage
			}
			cells := []string{j.CreatedAt.Format("Jan 2, 2006"), string(j.Status), j.PayerName, fmt.Sprintf("%d", j.AttemptCount), truncate(summary, 40)}
			for i, c := range cells {
				f.CellFormat(widths[i], 6, c, "1", 0, "L", false, 0, "")
			}
			f.Ln(-1)
		}
	}
	footer(f)
	return f.Output(w)
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n-1] + "..."
}

// ReportPDF renders the practice-wide analytics snapshot shown on the Reports page.
func ReportPDF(w io.Writer, st *db.Stats) error {
	f := newDoc("Practice Report")
	header(f, "Practice Report", time.Now().Format("January 2, 2006"))

	sectionTitle(f, "Summary")
	kv(f, "Total verifications", fmt.Sprintf("%d", st.Total))
	kv(f, "Verified", fmt.Sprintf("%d", st.Verified))
	kv(f, "Coverage gap flagged", fmt.Sprintf("%d", st.GapFlagged))
	kv(f, "In progress", fmt.Sprintf("%d", st.InProgress))
	kv(f, "Needs manual review", fmt.Sprintf("%d", st.NeedsReview))
	kv(f, "Success rate", fmt.Sprintf("%.1f%%", st.SuccessRate))
	kv(f, "Avg. processing time", fmt.Sprintf("%.1f seconds", st.AvgProcessSecs))
	f.Ln(4)

	sectionTitle(f, "By payer")
	if len(st.ByPayer) == 0 {
		f.SetFont("Helvetica", "I", 9)
		f.SetTextColor(mutedR, mutedG, mutedB)
		f.CellFormat(0, 6, "No data yet.", "", 1, "L", false, 0, "")
	} else {
		for _, p := range st.ByPayer {
			kv(f, p.Payer, fmt.Sprintf("%d verifications", p.Count))
		}
	}
	f.Ln(4)

	sectionTitle(f, "Last 7 days")
	for _, d := range st.Last7Days {
		kv(f, d.Day, fmt.Sprintf("%d verifications", d.Count))
	}
	footer(f)
	return f.Output(w)
}
